


Neurofeedback training denotes training brain activity towards some desired state by means of a real time feedback. This is a somewhat established clinical practice but consumer neurofeedback systems remain rare. This thesis explores the feasibility of a neurofeedback system comprising of a low cost consumer BCI and a mobile device through the design, implementation and evaluation of AlphaTrainer. It is concluded that the MindWave Mobile BCI is feasible for building an alpha feedback system based on its ability to measure alpha wave activity. A user evaluation of AlphaTrainer verifies the feasibility of performing neurofeedback training in an everyday context. However, the need for a longitudinal study of AlphaTrainer's training effect remains.
