\newlabel{appendix_background_testbench::doc}
\newlabel{appendix_background_testbench:appendix-background-testbench}
\newlabel{appendix_background_testbench:emotiv-epoc-testbench}
\newlabel{appendix_background_truesense_console::doc}
\newlabel{appendix_background_truesense_console:appendix-background-truesense-console}
\newlabel{appendix_background_truesense_console:truesense-kit-console}
\newlabel{appendix_design_personas::doc}
\newlabel{appendix_design_personas:appendix-design-personas}
\newlabel{appendix_design_personas:design-personas}
\newlabel{appendix_design_personas:morten}
\newlabel{appendix_design_personas:niels}
\newlabel{appendix_design_personas:olivia}
\newlabel{appendix_design_personas:personas}
\newlabel{appendix_design_personas:peter}
\newlabel{appendix_design_storyboards::doc}
\newlabel{appendix_design_storyboards:appendix-design-storyboards}
\newlabel{appendix_design_storyboards:design-storyboards}
\newlabel{appendix_evaluation::doc}
\newlabel{appendix_evaluation:appendix-final-evaluation-hand-out}
\newlabel{appendix_evaluation:appendix-final-evaluation-ordered-baseline-recordings}
\newlabel{appendix_evaluation:appendix-final-evaluation}
\newlabel{appendix_evaluation:hand-out}
\newlabel{appendix_evaluation:ordered-baseline-recordings}
\newlabel{appendix_evaluation:user-evaluation}
\newlabel{appendix_experiment::doc}
\newlabel{appendix_experiment:appendix-experiment}
\newlabel{appendix_experiment:download-code}
\newlabel{appendix_experiment:experiment-signal-processing}
\newlabel{appendix_experiment:load-and-run}
\newlabel{appendix_experiment:prerequests}
\newlabel{appendix_experiment:run-analysis}
\newlabel{appendix_experiment_mindwave_fora_posts::doc}
\newlabel{appendix_experiment_mindwave_fora_posts:appendix-experiment-mindwave-fora-posts}
\newlabel{appendix_experiment_mindwave_fora_posts:mindwave-forum-posts}
\newlabel{appendix_software::doc}
\newlabel{appendix_software:alphatrainer-android-app}
\newlabel{appendix_software:alphatrainer-signal-processing-library}
\newlabel{appendix_software:alphatrainerservice-client}
\newlabel{appendix_software:alphatrainerservice}
\newlabel{appendix_software:appendix-alphatrainer-android-app}
\newlabel{appendix_software:appendix-alphatrainer-mongolab-cloud-storage}
\newlabel{appendix_software:appendix-alphatrainer-service}
\newlabel{appendix_software:appendix-alphatrainer-signal-processing-library}
\newlabel{appendix_software:appendix-alphatrainerservice-client}
\newlabel{appendix_software:appendix-software}
\newlabel{appendix_software:build-from-scratch}
\newlabel{appendix_software:load-and-run}
\newlabel{appendix_software:mongolab-cloud-storage}
\newlabel{appendix_software:prerequests}
\newlabel{appendix_software:quick}
\newlabel{appendix_software:software}
\newlabel{ch-background/index::doc}
\newlabel{ch-background/index:background}
\newlabel{ch-background/index:bci-eeg}
\newlabel{ch-background/index:biozen}
\newlabel{ch-background/index:brainball}
\newlabel{ch-background/index:ch-background-bio-zen}
\newlabel{ch-background/index:ch-background-brain-ball}
\newlabel{ch-background/index:ch-background-consumer-bcis}
\newlabel{ch-background/index:ch-background-epoc}
\newlabel{ch-background/index:ch-background-future-headsets}
\newlabel{ch-background/index:ch-background-mindwave}
\newlabel{ch-background/index:ch-background-smartphone-brain-scanner-2}
\newlabel{ch-background/index:ch-background-truesense-kit}
\newlabel{ch-background/index:ch-background}
\newlabel{ch-background/index:classic-bci-applications-and-techniques}
\newlabel{ch-background/index:consumer-bcis}
\newlabel{ch-background/index:emotiv-epoc}
\newlabel{ch-background/index:fig-background-biozen-app-feedback}
\newlabel{ch-background/index:fig-background-biozen-feedback-gain-control}
\newlabel{ch-background/index:fig-background-biozen-feedback-save}
\newlabel{ch-background/index:fig-background-biozen-feedback}
\newlabel{ch-background/index:fig-background-consumer-bcis-epoc}
\newlabel{ch-background/index:fig-background-consumer-bcis-images}
\newlabel{ch-background/index:fig-background-consumer-bcis-images}
\newlabel{ch-background/index:fig-background-consumer-bcis-mindwave}
\newlabel{ch-background/index:fig-background-consumer-bcis-truesense}
\newlabel{ch-background/index:fig-background-eeg-raw-fft}
\newlabel{ch-background/index:fig-background-mindwave-eeg-fft}
\newlabel{ch-background/index:fig-background-mindwave-eeg-raw}
\newlabel{ch-background/index:fig-bci-classic-cap-martin-pelle}
\newlabel{ch-background/index:fig-bci-related-mindball-game}
\newlabel{ch-background/index:fig-eeg-with-alpha-waves}
\newlabel{ch-background/index:fig-related-smartphone-brain-scanner-feedback}
\newlabel{ch-background/index:future-headsets}
\newlabel{ch-background/index:neurofeedback-in-practice}
\newlabel{ch-background/index:neurofeedback}
\newlabel{ch-background/index:neurosky-mindwave-mobile}
\newlabel{ch-background/index:related-works}
\newlabel{ch-background/index:sec-background-stress-alpha-feedback-training}
\newlabel{ch-background/index:sec-related-works}
\newlabel{ch-background/index:smartphone-brain-scanner-2}
\newlabel{ch-background/index:stress-and-alpha-feedback-training}
\newlabel{ch-background/index:sum-up-of-background-and-related-systems}
\newlabel{ch-background/index:table-background-frequency-bands}
\newlabel{ch-background/index:table-consumer-bcis}
\newlabel{ch-background/index:table-related-systems}
\newlabel{ch-background/index:truesense-kit}
\newlabel{ch-conclusion/index::doc}
\newlabel{ch-conclusion/index:ch-conclusion}
\newlabel{ch-conclusion/index:conclusion}
\newlabel{ch-conclusion/index:future-work}
\newlabel{ch-conclusion/index:sec-future-work}
\newlabel{ch-design/index::doc}
\newlabel{ch-design/index:alphatrainer}
\newlabel{ch-design/index:ch-design-alphatrainer}
\newlabel{ch-design/index:ch-design-model-and-method}
\newlabel{ch-design/index:ch-design-process}
\newlabel{ch-design/index:ch-design}
\newlabel{ch-design/index:design-model-and-method}
\newlabel{ch-design/index:design-process}
\newlabel{ch-design/index:design}
\newlabel{ch-design/index:early-functioning-android-prototype}
\newlabel{ch-design/index:fig-design-scenario-work}
\newlabel{ch-design/index:fig-early-prototype-app-screen-start}
\newlabel{ch-design/index:fig-early-prototype-feedback-bar-growing}
\newlabel{ch-design/index:fig-early-prototype-feedback-bar-w-history}
\newlabel{ch-design/index:fig-early-prototype-feedback-bar}
\newlabel{ch-design/index:fig-early-prototype-feedback-box-w-history}
\newlabel{ch-design/index:fig-early-prototype-feedback-box}
\newlabel{ch-design/index:fig-early-prototype-screen-calibrate}
\newlabel{ch-design/index:fig-early-prototype-screen-history}
\newlabel{ch-design/index:fig-early-prototype}
\newlabel{ch-design/index:fig-final-prototype-app-feedbacks}
\newlabel{ch-design/index:fig-final-prototype-app-flow-app-screen-start}
\newlabel{ch-design/index:fig-final-prototype-app-flow-calibrate-no-connect}
\newlabel{ch-design/index:fig-final-prototype-app-flow-calibrate-step-1}
\newlabel{ch-design/index:fig-final-prototype-app-flow-calibrate-step-2}
\newlabel{ch-design/index:fig-final-prototype-app-flow-no-headset-found}
\newlabel{ch-design/index:fig-final-prototype-app-flow-prototype-reference}
\newlabel{ch-design/index:fig-final-prototype-app-flow-training-completed}
\newlabel{ch-design/index:fig-final-prototype-app-flow-training-history}
\newlabel{ch-design/index:fig-final-prototype-app-flow-training-start}
\newlabel{ch-design/index:fig-final-prototype-app-flow}
\newlabel{ch-design/index:fig-final-prototype-feedback-1-box-colors}
\newlabel{ch-design/index:fig-final-prototype-feedback-2-circles}
\newlabel{ch-design/index:fig-final-prototype-feedback-3-4-5}
\newlabel{ch-design/index:fig-iterative-model}
\newlabel{ch-design/index:initial-experimental-prototype}
\newlabel{ch-evaluation/index::doc}
\newlabel{ch-evaluation/index:analysis-of-logged-data}
\newlabel{ch-evaluation/index:ch-evaluation}
\newlabel{ch-evaluation/index:data-logging}
\newlabel{ch-evaluation/index:method}
\newlabel{ch-evaluation/index:observation-and-interview}
\newlabel{ch-evaluation/index:participant-observation-and-a-semi-structured-interview}
\newlabel{ch-evaluation/index:participants}
\newlabel{ch-evaluation/index:result}
\newlabel{ch-evaluation/index:sum-up-of-results}
\newlabel{ch-evaluation/index:survey-results}
\newlabel{ch-evaluation/index:survey}
\newlabel{ch-evaluation/index:table-latin-square-feedbacks}
\newlabel{ch-evaluation/index:table-logged-data-avg-alpha-baseline-open-closed-eyes-per-user}
\newlabel{ch-evaluation/index:table-logged-data-avg-alpha-baseline-per-user}
\newlabel{ch-evaluation/index:table-logged-data-avg-alpha-baseline-per-user}
\newlabel{ch-evaluation/index:table-micro-questionary-result}
\newlabel{ch-evaluation/index:user-evaluation}
\newlabel{ch-experiment/index-eq-absolute-alpha}
\newlabel{ch-experiment/index-eq-relative-alpha}
\newlabel{ch-experiment/index::doc}
\newlabel{ch-experiment/index:ch-experiment-pre-study}
\newlabel{ch-experiment/index:ch-experiment-processing}
\newlabel{ch-experiment/index:ch-experiment}
\newlabel{ch-experiment/index:choice-of-bci}
\newlabel{ch-experiment/index:data-processing-cleaning-and-analysis}
\newlabel{ch-experiment/index:equation-eq-absolute-alpha}
\newlabel{ch-experiment/index:equation-eq-relative-alpha}
\newlabel{ch-experiment/index:evaluation-of-3-consumer-bcis}
\newlabel{ch-experiment/index:execution}
\newlabel{ch-experiment/index:experiment-design}
\newlabel{ch-experiment/index:fig-early-open-closed-experiments}
\newlabel{ch-experiment/index:fig-experiment-alpha-bin-2s-raw-eeg}
\newlabel{ch-experiment/index:fig-experiment-alpha-bin-2s-sdk}
\newlabel{ch-experiment/index:fig-experiment-final-13-emotiv-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-13-emotiv-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-final-13-mindwave-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-13-mindwave-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-final-13-truesense-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-13-truesense-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-final-7-emotiv-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-7-emotiv-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-final-7-mindwave-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-7-mindwave-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-final-7-truesense-alpha-power}
\newlabel{ch-experiment/index:fig-experiment-final-7-truesense-alpha-progress}
\newlabel{ch-experiment/index:fig-experiment-setup-w-epoc}
\newlabel{ch-experiment/index:fig-experiment-setup-w-mindwave}
\newlabel{ch-experiment/index:fig-experiment-setup-w-sense}
\newlabel{ch-experiment/index:fig-experiment-setup}
\newlabel{ch-experiment/index:fig-final-experiment-recording-13}
\newlabel{ch-experiment/index:fig-final-experiment-recording-13}
\newlabel{ch-experiment/index:fig-final-experiment-recording-7}
\newlabel{ch-experiment/index:fig-mindwave-sdk-low-alpha-power}
\newlabel{ch-experiment/index:fig-mindwave-sdk-values}
\newlabel{ch-experiment/index:fig-mindwave-sdk-y-lim-30000}
\newlabel{ch-experiment/index:pre-study}
\newlabel{ch-experiment/index:table-bci-evaluation}
\newlabel{ch-experiment/index:table-experiment-final-relaxed-comfort}
\newlabel{ch-experiment/index:table-experiment-final-relaxed-comfort}
\newlabel{ch-experiment/index:table-experiment-final-result-mean}
\newlabel{ch-experiment/index:table-experiment-headset-latin-square}
\newlabel{ch-experiment/index:table-experiment-headset-latin-square}
\newlabel{ch-implementation/index::doc}
\newlabel{ch-implementation/index:alphatrainserservice-client}
\newlabel{ch-implementation/index:android-app}
\newlabel{ch-implementation/index:ch-implementation-alphatrainer-cloud-based-storage}
\newlabel{ch-implementation/index:ch-implementation-alphatrainer-service-client}
\newlabel{ch-implementation/index:ch-implementation-feedback-ui-s}
\newlabel{ch-implementation/index:ch-implementation-models-persistent-storage}
\newlabel{ch-implementation/index:ch-implementation-signal-processing-library}
\newlabel{ch-implementation/index:ch-implementation}
\newlabel{ch-implementation/index:cloud-based-storage}
\newlabel{ch-implementation/index:data-flow}
\newlabel{ch-implementation/index:feedback-user-interfaces}
\newlabel{ch-implementation/index:fig-alpha-trainer-service}
\newlabel{ch-implementation/index:fig-flow-diagram-feedback}
\newlabel{ch-implementation/index:fig-implementation-alphatrainer-android-app-architecture}
\newlabel{ch-implementation/index:fig-implementation-alphatrainer-system-overview}
\newlabel{ch-implementation/index:headset}
\newlabel{ch-implementation/index:implementation}
\newlabel{ch-implementation/index:models-and-persistent-storage}
\newlabel{ch-implementation/index:overview}
\newlabel{ch-implementation/index:signal-processing-library}
\newlabel{ch-implementation/index:signal-processing}
\newlabel{ch-implementation/index:state-management}
\newlabel{ch-implementation/index:summary}
\newlabel{ch-intro/index::doc}
\newlabel{ch-intro/index:ch-intro-hypothesis-goals}
\newlabel{ch-intro/index:ch-intro-limitations}
\newlabel{ch-intro/index:ch-intro-method}
\newlabel{ch-intro/index:ch-intro-neurofeedback-stress-and-bci}
\newlabel{ch-intro/index:ch-intro-thesis-overview}
\newlabel{ch-intro/index:ch-intro}
\newlabel{ch-intro/index:fig-muse-headband}
\newlabel{ch-intro/index:fig-triangulation}
\newlabel{ch-intro/index:hypothesis}
\newlabel{ch-intro/index:introduction}
\newlabel{ch-intro/index:limitations}
\newlabel{ch-intro/index:method}
\newlabel{ch-intro/index:neurofeedback-stress-and-brain-computer-interfaces}
\newlabel{ch-intro/index:thesis-overview}
\newlabel{index_tex::doc}
\newlabel{sub@ch-background/index:fig-background-biozen-feedback-gain-control}
\newlabel{sub@ch-background/index:fig-background-biozen-feedback-save}
\newlabel{sub@ch-background/index:fig-background-biozen-feedback}
\newlabel{sub@ch-background/index:fig-background-consumer-bcis-epoc}
\newlabel{sub@ch-background/index:fig-background-consumer-bcis-mindwave}
\newlabel{sub@ch-background/index:fig-background-consumer-bcis-truesense}
\newlabel{sub@ch-background/index:fig-background-mindwave-eeg-fft}
\newlabel{sub@ch-background/index:fig-background-mindwave-eeg-raw}
\newlabel{sub@ch-design/index:fig-early-prototype-app-screen-start}
\newlabel{sub@ch-design/index:fig-early-prototype-feedback-bar-growing}
\newlabel{sub@ch-design/index:fig-early-prototype-feedback-bar-w-history}
\newlabel{sub@ch-design/index:fig-early-prototype-feedback-bar}
\newlabel{sub@ch-design/index:fig-early-prototype-feedback-box-w-history}
\newlabel{sub@ch-design/index:fig-early-prototype-feedback-box}
\newlabel{sub@ch-design/index:fig-early-prototype-screen-calibrate}
\newlabel{sub@ch-design/index:fig-early-prototype-screen-history}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-app-screen-start}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-calibrate-no-connect}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-calibrate-step-1}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-calibrate-step-2}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-no-headset-found}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-prototype-reference}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-training-completed}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-training-history}
\newlabel{sub@ch-design/index:fig-final-prototype-app-flow-training-start}
\newlabel{sub@ch-design/index:fig-final-prototype-feedback-1-box-colors}
\newlabel{sub@ch-design/index:fig-final-prototype-feedback-2-circles}
\newlabel{sub@ch-design/index:fig-final-prototype-feedback-3-4-5}
\newlabel{sub@ch-experiment/index:fig-experiment-alpha-bin-2s-raw-eeg}
\newlabel{sub@ch-experiment/index:fig-experiment-alpha-bin-2s-sdk}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-emotiv-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-emotiv-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-mindwave-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-mindwave-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-truesense-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-13-truesense-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-emotiv-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-emotiv-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-mindwave-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-mindwave-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-truesense-alpha-power}
\newlabel{sub@ch-experiment/index:fig-experiment-final-7-truesense-alpha-progress}
\newlabel{sub@ch-experiment/index:fig-experiment-setup-w-epoc}
\newlabel{sub@ch-experiment/index:fig-experiment-setup-w-mindwave}
\newlabel{sub@ch-experiment/index:fig-experiment-setup-w-sense}
\newlabel{sub@ch-experiment/index:fig-mindwave-sdk-low-alpha-power}
\newlabel{sub@ch-experiment/index:fig-mindwave-sdk-y-lim-30000}
